name: CD - Build & Push Docker Image

on:
  push:
    branches: [ "estado" ]

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build da imagem
        run: docker build -t ghcr.io/${{ github.repository_owner }}/testeapi:latest .

      - name: Push
        run: docker push ghcr.io/${{ github.repository_owner }}/testeapi:latest
